# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "News"
  url = "post"
  weight = 20

[[main]]
  name = "People"
  url = "people"
  weight = 30

[[main]]
  name = "Research"
  identifier = "research"
  url = "research/"
  weight = 40

[[main]]
  name = "Publications"
  url = "publication"
  weight = 50
  
  
[[main]]
  name = "Join"
  identifier = "join"
  url = "join"
  weight = 60

[[main]]
  name = "Prospective Students"
  parent = "join"
  url = "join/prospective_students"
  weight = 1
  
[[main]]
  name = "Current Openings"
  parent = "join"
  url = "join/current_openings"
  weight = 2

  
[[main]]
  name = "Contact"
  url = "contact"
  weight = 70

[[main]]
  name = "Sounds of Nature"
  identifier = "welcome"
  url = "sounds"
  weight = 80
  
[[main]]
  name = "About"
  parent = "Sounds of Nature"
  url = "sounds/about"
  weight = 1
  
[[main]]
  name = "Saluki BioBlitz"
  identifier = "bioblitz"
  url = "bioblitz/"
  weight = 90
